//Exercise #1

When a Mule app starts, a connectivity test runs on components (such as the HTTP or FTP connector) that need to connect to an external server. 
// instead of blocking the deployment
If the test fails, the default behavior is to log a warning message and continue with the deployment of the app.

// Look at making a simple table here 
You can modify this behavior by setting the following parameters:

// Note that the first two params are either/or
* Reconnect (`reconnect`): Sets the number of reconnection attempts (after an initial failure) and the interval at which to execute them. The default is two reconnection attempts at a frequency of 2000 ms.

* Reconnect Forever (`reconnect-forever`): Sets the number of reconnection attempts to be unlimited, at a given interval. The default frequency for this parameter is 2000 ms, and the default value is false.

* Fail Deployment (`failsDeployment`): Forces the deployment to fail if all connection attempts fail (rather than logging a warning message and continuing with the deployment of the app).  The default for this parameter is false.

The following example sets the deployment to fail after five reconnection attempts:

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----


The following example does not set a limit on the number of reconnection attempts:

[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000"/>
  </reconnection>
</http:request-connectio>
----
