//Exercise #1

= Connecting to your Mule app
//Provide a brief gist of what this task will help the user achieve and who is the persona using this information.
//Check with developer on system requirements and environment (on-prem vs cloud) and provide that information as a prerequsite step.
//Steps to connect to the MuleSoft app.

Once you connect to the Mule app the system runs connectivity tests on components in the backend based on certain parameters such as the HTTP or FTP connector that requires connection to an external server. In case the test fails, the system logs a warning message and continues with the deployment of the app, instead of blocking the deployment.

You can modify this behavior by configuring the settings to define the number of reconnection attempts after an initial failure and force the deployment to fail when all connection attempts fail. You can use the following parameter settings: 

* **Fail Deployment (`failsDeployment`)**: Forces the deployment to fail if the connection fails and if all configured reconection attempts are exhausted.
* ** Reconnect (`reconnect`)**: Limits the number of reconnection attempts and the interval to execute them in. 
+
For example, you might set a count of 5 reconnection attempts at a `frequency` of every `4000` milliseconds (ms), which defaults to 2 reconnection attempts at a frequency of `2000ms`. Refer to the code below for more information:
+
[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----

* ** Reconnect Forever (`reconnect-forever`)**: Attempts to reconnect at a given interval, for example, every 4000 ms for as long as the app runs. Defaults to every 2000 ms. Because there is no limit on the number of retries, no value for count is specified.
+
Example that does not set a limit on the number of reconnection attempts:
+
[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection>
</http:request-connectio>
----
