//Exercise #1

When a Mule app starts, a connectivity test runs on components such as HTTP or FTP connector that need to connect to an external server. If the test fails, the default behavior is to log a warning message and continue with the deployment of the app instead of blocking it.

You can modify this behavior by setting the number of reconnection attempts after an initial failure and forcing the deployment to fail when all connection attempts fail.

* Fail Deployment (`failsDeployment`): Forces the deployment to fail if the connection fails. No reconection attempts are allowed.
* Reconnect (`reconnect`): Limits the number of reconnection attempts and the interval at which to execute them. For example, you may set a count of 5 reconnection attempts at a `frequency` of `4000` milliseconds (ms). The defaults is 2 reconnection attempts at a frequency of `2000` ms.
+
Example of a failed deployment after 5 reconnection attempts are exhausted:
+
[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="jsonplaceholder.typicode.com" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----

* Reconnect Forever (`reconnect-forever`): Attempts to reconnect at a given interval, for example every `4000` ms, as long as the app runs. The default frequency is 2000 ms. Since there is no limit on the number of retries, a value for count is not specified.
+
Example that does not set a limit on the number of reconnection attempts:
+
[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
 <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" count=""/>
  </reconnection>
 </http:request-connection>
</http:request-config>
----
