//Exercise #1

= Setting reconnection attempts

When a Mule app starts, a connectivity test runs on components like the HTTP or FTP connector that need to connect to an external server. If the test fails, the default behavior is to log a warning message and continue with the deployment of the app instead of blocking the deployment.

If the reconnection fails initially, set the number of reconnection attempts.

* `failsDeployment`: Forces the deployment to fail if all reconnection attempts fail.
* `reconnect`: Limits the number of reconnection attempts and the interval at which to execute them. For example, you might set a count of 5 reconnection attempts at a `frequency` of every `4000` milliseconds (ms). Defaults to 2 reconnection attempts at a frequency of `2000ms`.


== Example that fails after 5 reconnection attempts are exhausted

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="<https://jsonplaceholder.typicode.com/posts>" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----

* Replace `<https://jsonplaceholder.typicode.com/posts>` with your JSON request URL.

== Example of a number of reconnection attempts with no limits

`reconnect-forever`: Attempts to reconnect at a given interval, for example, every 4000 ms for as long as the app runs. Defaults to every 2000 ms. Because there is no limit on the number of retries, no value for count is specified.

[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000" count=”5”/>
  </reconnection>
</http:request-connection>
----
