//Exercise #1
# Configuring a reconnection strategy

When a Mule application starts, a connectivity test runs on components, such as the HTTP or FTP connector. When the connectivity test to the external server fails,  a warning message appears and deploymnet of the application continues by default. You can also optionally block the deployment of the application based on your needs by configuring a reconnection strategy. 

You can set the number of reconnection attempts to try after an initial failure and force the deployment to fail when all connection attempts fail.
To change the default behaviour, use the following parameters:

* Fail Deployment (`failsDeployment`):  When you set this parameter as `True`, it forces the deployment to fail when the connection test fails and any configured reconnection attempts are exhausted. 
* Reconnect (`reconnect`):  When you set this parameter with the reconnect frequencey and number of attempts, it limits the number of reconnection attempts and the interval at which to execute them. For example, you might set a count of five reconnection attempts at a `frequency` of every `4000` milliseconds (ms). The default behaviour is set as two reconnection attempts at a frequency of `2000ms`. 
* Reconnect Forever (reconnect-forever): This parameter attempts to reconnect at a given interval. For example, it tries to reconnect every `4000ms` as long as the app runs. The default value is 2000 ms. Because there is no limit on the number of retries, no value for count is specified.

## Example: Configuring a reconnection strategy using the number of connection attempts

The following is a configuration example for a Mule application deployment with a reconnection strategy by specifying the number of connection attempts. In this example, the application deployment fails after five reconnection attempts are exhausted. 

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000"  count=”5” />
    </reconnection
  </http:request-connection>
</http:request-config>
----

##  Example: Configuring a reconnection strategy using connection interval 

The following is a configuration example for a Mule application deployment with a reconnection strategy by specifying only the interval.
This example does not set a limit on the number of reconnection attempts.

[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000">
  </reconnection>
</http:request-connectio>
----
